version: '3.8'

services:
  web:
    build: .
    container_name: soltech_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/
      - ./config/custom.ini:/usr/local/etc/php/conf.d/custom.ini  # <--- ADICIONE ESTA LINHA
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_PORT=5432

  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:13-alpine
    container_name: soltech_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql # Executa o script SQL na inicialização
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432" # Expõe a porta do banco no host (opcional, bom para debugar)

volumes:
  postgres_data: